export const GOT_ALL_ARTICLES = 'GOT_ALL_ARTICLES';
export const GOT_MY_ARTICLES = 'GOT_MY_ARTICLES';
export const GOT_SINGLE_ARTICLE = 'GOT_SINGLE_ARTICLE';
export const GOT_CART_ARTICLES = 'GOT_CART_ARTICLES';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_WEB3MODAL = 'SET_WEB3MODAL';
export const SET_WEB3INST = 'SET_WEB3INST';
export const SET_ACCOUNT = 'SET_ACCOUNT';

export const SET_LOOT_CONTRACT = "SET_LOOT_CONTRACT";
export const SET_MINT_CONTRACT = "SET_MINT_CONTRACT";
export const SET_STAKING_CONTRACT = "SET_STAKING_CONTRACT";
export const SET_LOOT_BALANCE = "SET_LOOT_BALANCE";